spring:
  cloud:
    gateway:
      routes:
          - id: user_route
            uri: http://www.baidu.com
            predicates:
              - Path=/user/**
            filters:
              - StripPrefix=1
      discovery:
        locator:
          enabled: true
  redis:
    jedis:
      pool:
        max-active: 100
        max-wait: 10000
        max-idle: 10
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
  application:
    name: gateway-web
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true